# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "10.0"

    steps:
      - run:
          name: Wait 1 Second (Need to increment to 900 soon)
          command: sleep 1
      - checkout
      - run:
          name: Bump Version & Push To Repo
          command: |
             cd scripts
             php version-bumper-ios.php
             chmod 777 ../SmartReceipts/SmartReceipts-Info.plist
             printf "\n"
             echo "-- Pushing To Github --"
             printf "\n"
             git config credential.helper 'cache --timeout=120'
             git config user.email "tom@kidonpoint.com"
             git config user.name "tomgs"
             git add ../SmartReceipts/SmartReceipts-Info.plist
             git commit -m "Bumping Project Version [ci skip]"
             cd ..
             git push -q https://${GITHUB_API_TOKEN}@github.com/tomgs/SmartReceiptsiOS.git ${CIRCLE_BRANCH}
      # Update CocoaPods
      - run:
          name: Update CocoaPods
          command: pod repo update
      # Install CocoaPods
      - run:
          name: Install CocoaPods
          command: pod install

      # Build the app and run tests
      - run:
          name: Build and run tests
          command: fastlane scan --scheme "SmartReceipts"
          environment:
            SCAN_DEVICE: iPhone X
            SCAN_SCHEME: WebTests

      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs